/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.Gato;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro RG
 */
public class FrmTablero extends javax.swing.JFrame {

    FrmAcercaDe frmAcercaDe1 = new FrmAcercaDe();
    private FrmIntro frmIntro;
    private Gato gato;
    private JLabel[] tablero;

    /**
     * Creates new form FrmTablero Se crea el arreglo del tablero, que
     * representa cada una de los cuadros donde se puede insertar X o 0
     * dependiendo del turno.
     */
    public FrmTablero() {
        initComponents();
        gato = new Gato();
        tablero = new JLabel[9];
        tablero[0] = lblImagen1;
        tablero[1] = lblImagen2;
        tablero[2] = lblImagen3;
        tablero[3] = lblImagen4;
        tablero[4] = lblImagen5;
        tablero[5] = lblImagen6;
        tablero[6] = lblImagen7;
        tablero[7] = lblImagen8;
        tablero[8] = lblImagen9;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblImagen2 = new javax.swing.JLabel();
        lblImagen1 = new javax.swing.JLabel();
        lblImagen3 = new javax.swing.JLabel();
        lblImagen4 = new javax.swing.JLabel();
        lblImagen5 = new javax.swing.JLabel();
        lblImagen6 = new javax.swing.JLabel();
        lblImagen7 = new javax.swing.JLabel();
        lblImagen8 = new javax.swing.JLabel();
        lblImagen9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbltirador = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnAcercaDe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JuegoGato v1.0");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 102, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Juego del Gato");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblImagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcs_gato/vacia.png"))); // NOI18N
        lblImagen2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lblImagen2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen2MouseClicked(evt);
            }
        });

        lblImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcs_gato/vacia.png"))); // NOI18N
        lblImagen1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lblImagen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen1MouseClicked(evt);
            }
        });

        lblImagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcs_gato/vacia.png"))); // NOI18N
        lblImagen3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lblImagen3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen3MouseClicked(evt);
            }
        });

        lblImagen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcs_gato/vacia.png"))); // NOI18N
        lblImagen4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lblImagen4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen4MouseClicked(evt);
            }
        });

        lblImagen5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcs_gato/vacia.png"))); // NOI18N
        lblImagen5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lblImagen5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen5MouseClicked(evt);
            }
        });

        lblImagen6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcs_gato/vacia.png"))); // NOI18N
        lblImagen6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lblImagen6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen6MouseClicked(evt);
            }
        });

        lblImagen7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcs_gato/vacia.png"))); // NOI18N
        lblImagen7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lblImagen7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen7MouseClicked(evt);
            }
        });

        lblImagen8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcs_gato/vacia.png"))); // NOI18N
        lblImagen8.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lblImagen8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen8MouseClicked(evt);
            }
        });

        lblImagen9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcs_gato/vacia.png"))); // NOI18N
        lblImagen9.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lblImagen9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen9MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Tirador: ");

        lbltirador.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbltirador.setForeground(new java.awt.Color(255, 0, 0));
        lbltirador.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistrar.setText("Registrar datos");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnAcercaDe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAcercaDe.setText("Acerca de");
        btnAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaDeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbltirador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(246, 246, 246))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblImagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblImagen7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(lblImagen8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblImagen9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(158, 158, 158)
                                                .addComponent(lblImagen6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnAcercaDe, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                                .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblImagen5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addComponent(lblImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(btnRegistrar)))
                                .addGap(42, 42, 42)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnRegistrar)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImagen5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImagen6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImagen8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImagen7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImagen9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnNuevo)
                        .addGap(83, 83, 83)
                        .addComponent(btnAcercaDe)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltirador, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        gato.setPerTiro(true);
        frmIntro = new FrmIntro(gato);
        frmIntro.setVisible(true);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        lbltirador.setText(gato.getJugador1());
    }//GEN-LAST:event_formWindowActivated

    private void lblImagen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen1MouseClicked
        // TODO add your handling code here:
        tirar(0);
        gato.setCaro(true);
    }//GEN-LAST:event_lblImagen1MouseClicked

    private void lblImagen2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen2MouseClicked
        // TODO add your handling code here:
        tirar(1);
        gato.setCaro(true);
    }//GEN-LAST:event_lblImagen2MouseClicked

    private void lblImagen3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen3MouseClicked
        // TODO add your handling code here:
        tirar(2);
        gato.setCaro(true);
    }//GEN-LAST:event_lblImagen3MouseClicked

    private void lblImagen4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen4MouseClicked
        // TODO add your handling code here:
        tirar(3);
        gato.setCaro(true);
    }//GEN-LAST:event_lblImagen4MouseClicked

    private void lblImagen5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen5MouseClicked
        // TODO add your handling code here:
        tirar(4);
        gato.setCaro(true);
    }//GEN-LAST:event_lblImagen5MouseClicked

    private void lblImagen6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen6MouseClicked
        // TODO add your handling code here:
        tirar(5);
        gato.setCaro(true);
    }//GEN-LAST:event_lblImagen6MouseClicked

    private void lblImagen7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen7MouseClicked
        // TODO add your handling code here:
        tirar(6);
        gato.setCaro(true);
    }//GEN-LAST:event_lblImagen7MouseClicked

    private void lblImagen8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen8MouseClicked
        // TODO add your handling code here:
        tirar(7);
        gato.setCaro(true);
    }//GEN-LAST:event_lblImagen8MouseClicked

    private void lblImagen9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen9MouseClicked
        // TODO add your handling code here:
        tirar(8);
        gato.setCaro(true);
    }//GEN-LAST:event_lblImagen9MouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < 9; i++) {
            tablero[i].setIcon(new ImageIcon(getClass().getResource(
                    "/pcs_gato/vacia.png")));
        }
        gato.reiniciar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaDeActionPerformed
        // TODO add your handling code here:
        frmAcercaDe1.setVisible(true);
    }//GEN-LAST:event_btnAcercaDeActionPerformed

    /**
     * Este método se utiliza para hacer un tiro (Colocar una X o O) dentro de
     * una casilla disponible, además se verifica si en una fila o en una
     * columna se repite la misma figura (X u O) y dependiendo del turno, se
     * dara a conocer el ganador del juego o en todo caso si se llega a un
     * empate. Por último si se gana en vetical, horizontal o diagonal, se
     * pondra una linea para especificar como se gano.
     *
     * @param pos en este parametro se manda la poscición
     */
    private void tirar(int pos) {
        if (gato.ganador() == 0 && gato.getTiros() < 9 && gato.isPerTiro()) {
            gato.setTiro(pos);  // <------
            if (gato.isTurnoJ1()) {
                if (gato.getTiroJ1() == 1 && gato.isCaro() ) { // Equis
                    tablero[pos].setIcon(new ImageIcon(getClass().getResource(
                                "/pcs_gato/x.png")));
                } else { 
                    tablero[pos].setIcon(new ImageIcon(getClass().getResource(
                                "/pcs_gato/0.png")));
                }
            } else {
                if (gato.getTiroJ2() == 1 && gato.isCaro()) {
                    tablero[pos].setIcon(new ImageIcon(getClass().getResource(
                            "/pcs_gato/x.png")));
                } else {
                    tablero[pos].setIcon(new ImageIcon(getClass().getResource(
                            "/pcs_gato/0.png")));
                }
            }
            if (gato.ganador() != 0) {
                JOptionPane.showMessageDialog(this, "Ganó "
                        + lbltirador.getText() + "!!");
            } else if (gato.esEmpate()) {
                JOptionPane.showMessageDialog(this, "Es empate!!");
            } else {
                gato.cambiarTurno();
                if (gato.isTurnoJ1()) {
                    lbltirador.setText(gato.getJugador1());
                } else {
                    lbltirador.setText(gato.getJugador2());
                }
            }
        }
        //Cuando se gana, se verifica como se gano en el arreglo (Horizontal, 
        //vertical o diagonal) Y después se colocan las imagenes, representando
        //la linea en la dirección que se gano
        switch (gato.ganador()) {
            case 0:
                if (gato.esEmpate()) {
                    JOptionPane.showMessageDialog(this, "Es empate!!");
                }
                break;
            case 1:     //fila #1
                if (gato.isTurnoJ1()) {
                    if (gato.getTiroJ1() == 1) {
                        tablero[0].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_horizontal.png")));
                        tablero[1].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_horizontal.png")));
                        tablero[2].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_horizontal.png")));
                    } else {
                        tablero[0].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Horizontal.png")));
                        tablero[1].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Horizontal.png")));
                        tablero[2].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Horizontal.png")));
                    }
                } else {

                    if (gato.getTiroJ1() == 2) {
                        tablero[0].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_horizontal.png")));
                        tablero[1].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_horizontal.png")));
                        tablero[2].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_horizontal.png")));
                    } else {
                        tablero[0].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Horizontal.png")));
                        tablero[1].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Horizontal.png")));
                        tablero[2].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Horizontal.png")));
                    }
                }
                break;
            case 2:     //fila #2

                if (gato.isTurnoJ1()) {
                    if (gato.getTiroJ1() == 1) {
                        tablero[3].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_horizontal.png")));
                        tablero[4].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_horizontal.png")));
                        tablero[5].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_horizontal.png")));
                    } else {
                        tablero[3].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Horizontal.png")));
                        tablero[4].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Horizontal.png")));
                        tablero[5].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Horizontal.png")));
                    }
                } else {

                    if (gato.getTiroJ1() == 2) {
                        tablero[3].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_horizontal.png")));
                        tablero[4].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_horizontal.png")));
                        tablero[5].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_horizontal.png")));
                    } else {
                        tablero[3].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Horizontal.png")));
                        tablero[4].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Horizontal.png")));
                        tablero[5].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Horizontal.png")));
                    }

                }
                break;
            case 3:     //fila #3
                if (gato.isTurnoJ1()) {
                    if (gato.getTiroJ1() == 1) {
                        tablero[6].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_horizontal.png")));
                        tablero[7].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_horizontal.png")));
                        tablero[8].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_horizontal.png")));
                    } else {
                        tablero[6].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Horizontal.png")));
                        tablero[7].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Horizontal.png")));
                        tablero[8].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Horizontal.png")));
                    }
                } else {

                    if (gato.getTiroJ1() == 2) {
                        tablero[6].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_horizontal.png")));
                        tablero[7].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_horizontal.png")));
                        tablero[8].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_horizontal.png")));
                    } else {
                        tablero[6].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Horizontal.png")));
                        tablero[7].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Horizontal.png")));
                        tablero[8].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Horizontal.png")));
                    }

                }
                break;
            case 4:     //columna #1

                if (gato.isTurnoJ1()) {
                    if (gato.getTiroJ1() == 1) {
                        tablero[0].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_vertical.png")));
                        tablero[3].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_vertical.png")));
                        tablero[6].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_vertical.png")));
                    } else {
                        tablero[0].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Vertical.png")));
                        tablero[3].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Vertical.png")));
                        tablero[6].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Vertical.png")));
                    }
                } else {

                    if (gato.getTiroJ1() == 2) {
                        tablero[0].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_vertical.png")));
                        tablero[3].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_vertical.png")));
                        tablero[6].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_vertical.png")));
                    } else {
                        tablero[0].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Vertical.png")));
                        tablero[3].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Vertical.png")));
                        tablero[6].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Vertical.png")));
                    }

                }
                break;
            case 5:     //columna #2

                if (gato.isTurnoJ1()) {
                    if (gato.getTiroJ1() == 1) {
                        tablero[1].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_vertical.png")));
                        tablero[4].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_vertical.png")));
                        tablero[7].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_vertical.png")));
                    } else {
                        tablero[1].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Vertical.png")));
                        tablero[4].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Vertical.png")));
                        tablero[7].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Vertical.png")));
                    }
                } else {

                    if (gato.getTiroJ1() == 2) {
                        tablero[1].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_vertical.png")));
                        tablero[4].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_vertical.png")));
                        tablero[7].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_vertical.png")));
                    } else {
                        tablero[1].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Vertical.png")));
                        tablero[4].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Vertical.png")));
                        tablero[7].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Vertical.png")));
                    }

                }
                break;
            case 6:     //columna #3

                if (gato.isTurnoJ1()) {
                    if (gato.getTiroJ1() == 1) {
                        tablero[2].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_vertical.png")));
                        tablero[5].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_vertical.png")));
                        tablero[8].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_vertical.png")));
                    } else {
                        tablero[2].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Vertical.png")));
                        tablero[5].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Vertical.png")));
                        tablero[8].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Vertical.png")));
                    }
                } else {

                    if (gato.getTiroJ1() == 2) {
                        tablero[2].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_vertical.png")));
                        tablero[5].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_vertical.png")));
                        tablero[8].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_vertical.png")));
                    } else {
                        tablero[2].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Vertical.png")));
                        tablero[5].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Vertical.png")));
                        tablero[8].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Vertical.png")));
                    }

                }
                break;
            case 7:     //diagonal #1

                if (gato.isTurnoJ1()) {
                    if (gato.getTiroJ1() == 1) {
                        tablero[0].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_diagonal.png")));
                        tablero[4].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_diagonal.png")));
                        tablero[8].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_diagonal.png")));
                    } else {
                        tablero[0].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Diagonal.png")));
                        tablero[4].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Diagonal.png")));
                        tablero[8].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Diagonal.png")));
                    }
                } else {

                    if (gato.getTiroJ1() == 2) {
                        tablero[0].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_diagonal.png")));
                        tablero[4].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_diagonal.png")));
                        tablero[8].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_diagonal.png")));
                    } else {
                        tablero[0].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Diagonal.png")));
                        tablero[4].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Diagonal.png")));
                        tablero[8].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Diagonal.png")));
                    }
                }
                break;
            case 8:     //diagonal #2

                if (gato.isTurnoJ1()) {
                    if (gato.getTiroJ1() == 1) {
                        tablero[2].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_diagonal2.png")));
                        tablero[4].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_diagonal2.png")));
                        tablero[6].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_diagonal2.png")));
                    } else {
                        tablero[2].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Diagonal2.png")));
                        tablero[4].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Diagonal2.png")));
                        tablero[6].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Diagonal2.png")));
                    }
                } else {
                    if (gato.getTiroJ1() == 2) {
                        tablero[2].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_diagonal2.png")));
                        tablero[4].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_diagonal2.png")));
                        tablero[6].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/x_diagonal2.png")));
                    } else {
                        tablero[2].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Diagonal2.png")));
                        tablero[4].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Diagonal2.png")));
                        tablero[6].setIcon(new ImageIcon(getClass()
                                .getResource("/pcs_gato/0_Diagonal2.png")));
                    }
                }
                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcercaDe;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblImagen2;
    private javax.swing.JLabel lblImagen3;
    private javax.swing.JLabel lblImagen4;
    private javax.swing.JLabel lblImagen5;
    private javax.swing.JLabel lblImagen6;
    private javax.swing.JLabel lblImagen7;
    private javax.swing.JLabel lblImagen8;
    private javax.swing.JLabel lblImagen9;
    private javax.swing.JLabel lbltirador;
    // End of variables declaration//GEN-END:variables
}
